{{ if eq .Values.tools.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: {{ .Values.tools.namespace }}
  labels:
    jaeger-infra: jaeger-service
spec:
  ports:
    - name: query-http
      port: 80
      protocol: TCP
      targetPort: 16686
  selector:
    jaeger-infra: jaeger-pod
  type: LoadBalancer
{{end}}
