{{if eq .Values.istio.istioProvider "ossm3"}}
apiVersion: sailoperator.io/v1alpha1
kind: Istio
metadata:
  name: default
spec:
  namespace: {{ .Values.istio.namespace }}
  values:
    pilot:
      autoscaleMin: 2
  version: {{ .Values.istio.ossm3.version }}
{{end}}