apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant-operator
  namespace: {{ .Values.kuadrant.namespace }}
spec:
  channel: {{ .Values.kuadrant.channel }}
  installPlanApproval: Automatic
  name: {{ .Values.kuadrant.operatorName }}
{{- if .Values.kuadrant.indexImage }}
  source: kuadrant-upstream
  sourceNamespace: {{ .Values.kuadrant.namespace }}
{{- else }}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
  config:
    env:
      - name: "AUTH_SERVICE_TIMEOUT"
        value: "500ms"
